# Generated by Django 4.0.5 on 2022-06-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=250)),
                ('password', models.TextField(max_length=250)),
                ('payment', models.TextField(max_length=250)),
            ],
        ),
    ]
