# Generated by Django 4.0.5 on 2022-06-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistprofileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='payment',
            field=models.IntegerField(),
        ),
    ]
