# Generated by Django 4.0.5 on 2022-06-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistprofileapp', '0002_alter_registration_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.TextField(max_length=250)),
                ('lastname', models.TextField(max_length=250)),
                ('gender', models.TextField(max_length=250)),
                ('image', models.TextField(max_length=250)),
                ('address', models.TextField(max_length=1000)),
            ],
        ),
    ]
