# Generated by Django 4.0.5 on 2022-06-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistprofileapp', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
